### ISSUE TITLE
生成2X图的时候，如果左上角的第一个图标是方的而且有背景色 ，那这个图片左上角4*4px的图案被掏空

### ISSUE THREAD

**Issue by ZhaoxinLiu** [laoshu133/css-spritesmith#1]
imageSetSpriteCreator.js这个文件里 前后占位是嘎嘛用的？place_before.png把图片左上角的图像替换了，若把module.exports里面的list.push(PLACE_IMAGE_BEFORE) 的push 改成unshift就没这个情况了

**Comment by laoshu133** [comment]
`PLACE_IMAGE` 是用来占位以保证 2x 图片宽高刚好是 1x 的两倍，
`layout` 不支持指定宽高来实现布局，这里使用了一个黑魔法让它按我们给定的宽高来布局；
两个占位的图片是透明的，正常来讲是不会影响生成的图片，你这个问题可能是渲染引擎的问题，方便给出你的配置和环境吗？

**Comment by ZhaoxinLiu** [comment]
return gulp.src(config.app.iconCSS)
    .pipe($.concat('sprite.css'))
    .pipe(gulp.dest('app/css/icon/'))
    .pipe($.cssSpritesmith({
        imagepath: './app/images/icons/',
        spritedest: 'app/images/icons/',
        spritepath: '../../images/',
        useimageset: true,
        newsprite: false,
        spritestamp: false,
        cssstamp: false
    })).pipe(gulp.dest('./'));

图片在这里 http://i4.piimg.com/511860/753c300b58dc182e.png
系统Mac os 10.11.5 
node 5.11.1

windows 也如此

**Comment by laoshu133** [comment]
依赖库 `spritesmith` 的问题，具体原因未查明；
先临时发布一个版本 `css-spritesmith@0.0.5` ，
未更新 `grunt-css-sprite` 和 `gulp-css-spritesmith` 依赖，如有需要明天可以发一版

https://github.com/laoshu133/css-spritesmith/commit/207a267b1ca8c2ab73d8d7dd19da3f2f21ce3976
